// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBonWNCxblGnVIEkFCl7aRr3bv19ezn-iI',
    appId: '1:843182479411:web:8f4e131c80df8e23bdab46',
    messagingSenderId: '843182479411',
    projectId: 'fasfoodd',
    authDomain: 'fasfoodd.firebaseapp.com',
    storageBucket: 'fasfoodd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVUzPaBNWLOpcW8sejXcbjnLFvnCiNVao',
    appId: '1:843182479411:android:d822ac0ae1b3368abdab46',
    messagingSenderId: '843182479411',
    projectId: 'fasfoodd',
    storageBucket: 'fasfoodd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsGdKmi-VSN_43dXjOA0O6DkQ8UGZyQqE',
    appId: '1:843182479411:ios:fa75ef375f05d909bdab46',
    messagingSenderId: '843182479411',
    projectId: 'fasfoodd',
    storageBucket: 'fasfoodd.appspot.com',
    iosBundleId: 'com.example.fasfood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsGdKmi-VSN_43dXjOA0O6DkQ8UGZyQqE',
    appId: '1:843182479411:ios:c017c97fe05d1aedbdab46',
    messagingSenderId: '843182479411',
    projectId: 'fasfoodd',
    storageBucket: 'fasfoodd.appspot.com',
    iosBundleId: 'com.example.fasfood.RunnerTests',
  );
}
